spring:
  main:
    allow-circular-references: true
  # 数据库配置
  datasource:
    username: root
    password: 123456
    # myjfs文件系统，对应元数据的数据库为juicefs
    url: jdbc:mysql://114.132.67.88:3307/juicefs?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    dispatch-options-request: true

  # 邮件模块配置
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # SMTP 服务器的端口
    port: 465
    # 配置邮箱用户名
    username: funduncan@qq.com
    # 配置密钥
    password: gnnousfyrinobbdb
    # 字符编码
    default-encoding: UTF-8
    # 协议
    protocol: smtp
    properties:
      mail:
        smtp:
          # SSL加密工厂
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
          socketFactory:
            port: 465
        # 表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

  servlet:
    multipart:
      # 启用http上传文件
      enabled: true
      # 单个文件最大大小
      max-file-size: 1024MB
      # 多个文件最大大小
      max-request-size: 5120MB
      # 刷盘阈值
      file-size-threshold: 512KB
      # 上传文件的临时目录
      location: /Users/zhangxiaorui/Desktop

# spring boot端口
server:
  port: 8080

logging:
  level:
    xdu.cloudnative.service.file : debug